name: CI Pipeline
on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - '*'
  schedule:
    - cron: "15 7 * * *" # Nightly build at 7:15 AM (UDT)
  workflow_dispatch:  # This enables manual triggering

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux-amd64]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check linux version
        run: uname -a
      - name: linux update nightly
        run: rustup install nightly
      - name: linux build (rustc)
        run: |
          ./fam
      - name: linux build (mrustc)
        run: |
          wget https://github.com/cgilliard/famc/releases/download/0.1.0/linux_output.tar.gz
          gzip -dc linux_output.tar.gz | tar xvf -
          ./fam clean
          ./fam --mrustc --with-mrustc=./famc/bin/mrustc --output=./famc/output
      - name: linux tests
        run: |
          ./fam clean
          ./fam fasttest
      - name: linux code coverage dependencies
        run: |
          cargo install grcov
          rustup component add llvm-tools-preview
      - name: code coverage
        run: |
          git clone https://anything:${{ secrets.FamPat }}@github.com/cgilliard/fam.git _coverage
          cd _coverage
          git config user.name "Coverage-Bot"
          git config user.email "noreply@pipeline.com"
          git checkout main
          ./fam clean
          ./fam coverage --update-docs
          git commit -am "Coverage-Bot: Updated repo (via main.yml script) Source Version is $GITHUB_SHA";
          if [[ "$GITHUB_EVENT_NAME" == "schedule" || "$GITHUB_EVENT_NAME" == "workflow_dispatch" ]]; then
          git push https://${{ secrets.FamPat }}@github.com/cgilliard/fam.git
          fi
      - name: linux bootstrap (mrustc)
        run: |
          if [[ "$GITHUB_EVENT_NAME" == "schedule" || "$GITHUB_EVENT_NAME" == "workflow_dispatch" ]]; then
            git clone https://github.com/cgilliard/famc famc_build
            cd famc_build
            ./build.sh
            cd ..
            ./fam clean
            ./fam --mrustc --with-mrustc=./famc_build/bin/mrustc --output=./famc_build/output
          fi

  macos:
    runs-on: macos-latest
    strategy:
      matrix:
        platform: [macos]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check macos version
        run: |
          sw_vers
      - name: macos update nightly
        run: |
          rustup install nightly
          brew install autoconf automake libtool gmp
          sudo mkdir -p /usr/local/lib
          sudo cp `brew --prefix gmp`/lib/libgmp.a /usr/local/lib
      - name: macos build (rustc)
        run: |
          ./fam
      - name: macos build (mrustc)
        run: |
          export CXX=/opt/homebrew/bin/g++-13
          export CC=/opt/homebrew/bin/gcc-13
          wget https://github.com/cgilliard/famc/releases/download/0.1.0/macos_output.tar.gz
          gzip -dc macos_output.tar.gz | tar xvf -
          ./fam clean
          ./fam --mrustc --with-mrustc=./famc/bin/mrustc --output=./famc/output
      - name: macos tests
        run: |
          ./fam clean
          ./fam fasttest
      - name: macos bootstrap (mrustc)
        run: |
          if [[ "$GITHUB_EVENT_NAME" == "schedule" || "$GITHUB_EVENT_NAME" == "workflow_dispatch" ]]; then
            git clone https://github.com/cgilliard/famc famc_build
            cd famc_build
            export CXX=/opt/homebrew/bin/g++-13
            export CC=/opt/homebrew/bin/gcc-13
            ./build.sh
            cd ..
            ./fam clean
            ./fam --mrustc --with-mrustc=./famc_build/bin/mrustc --output=./famc_build/output
          fi
